name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main  # Hoặc branch bạn muốn dùng để deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build MkDocs
      run: |
        mkdocs build

    - name: Deploy to Read the Docs
      run: curl -X POST -d "build=true" -d "token=$\{TOKEN\}" https://readthedocs.org/api/v2/webhook/$\{PROJECT_SLUG\}/$\{WEBHOOK_ID\}/
      env:
        TOKEN: $\{{ secrets.RTD_TOKEN }}
        PROJECT_SLUG: 'your-project-slug'
        WEBHOOK_ID: 'your-webhook-id'